// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: test_grpc.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPreviewImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetPreviewImageRequest) Reset() {
	*x = GetPreviewImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreviewImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewImageRequest) ProtoMessage() {}

func (x *GetPreviewImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewImageRequest.ProtoReflect.Descriptor instead.
func (*GetPreviewImageRequest) Descriptor() ([]byte, []int) {
	return file_test_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetPreviewImageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetPreviewImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *GetPreviewImageResponse) Reset() {
	*x = GetPreviewImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreviewImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewImageResponse) ProtoMessage() {}

func (x *GetPreviewImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewImageResponse.ProtoReflect.Descriptor instead.
func (*GetPreviewImageResponse) Descriptor() ([]byte, []int) {
	return file_test_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetPreviewImageResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type GetPreviewImageSliceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *GetPreviewImageSliceRequest) Reset() {
	*x = GetPreviewImageSliceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreviewImageSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewImageSliceRequest) ProtoMessage() {}

func (x *GetPreviewImageSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewImageSliceRequest.ProtoReflect.Descriptor instead.
func (*GetPreviewImageSliceRequest) Descriptor() ([]byte, []int) {
	return file_test_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetPreviewImageSliceRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type GetPreviewImageSliceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images [][]byte `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *GetPreviewImageSliceResponse) Reset() {
	*x = GetPreviewImageSliceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPreviewImageSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewImageSliceResponse) ProtoMessage() {}

func (x *GetPreviewImageSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewImageSliceResponse.ProtoReflect.Descriptor instead.
func (*GetPreviewImageSliceResponse) Descriptor() ([]byte, []int) {
	return file_test_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetPreviewImageSliceResponse) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_test_grpc_proto protoreflect.FileDescriptor

var file_test_grpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x22, 0x2a, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x31, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x36, 0x0a, 0x1c, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x32, 0xcb, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_test_grpc_proto_rawDescOnce sync.Once
	file_test_grpc_proto_rawDescData = file_test_grpc_proto_rawDesc
)

func file_test_grpc_proto_rawDescGZIP() []byte {
	file_test_grpc_proto_rawDescOnce.Do(func() {
		file_test_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_grpc_proto_rawDescData)
	})
	return file_test_grpc_proto_rawDescData
}

var file_test_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test_grpc_proto_goTypes = []any{
	(*GetPreviewImageRequest)(nil),       // 0: preview.GetPreviewImageRequest
	(*GetPreviewImageResponse)(nil),      // 1: preview.GetPreviewImageResponse
	(*GetPreviewImageSliceRequest)(nil),  // 2: preview.GetPreviewImageSliceRequest
	(*GetPreviewImageSliceResponse)(nil), // 3: preview.GetPreviewImageSliceResponse
}
var file_test_grpc_proto_depIdxs = []int32{
	0, // 0: preview.PreviewService.GetPreviewImage:input_type -> preview.GetPreviewImageRequest
	2, // 1: preview.PreviewService.GetPreviewImageSlice:input_type -> preview.GetPreviewImageSliceRequest
	1, // 2: preview.PreviewService.GetPreviewImage:output_type -> preview.GetPreviewImageResponse
	3, // 3: preview.PreviewService.GetPreviewImageSlice:output_type -> preview.GetPreviewImageSliceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_grpc_proto_init() }
func file_test_grpc_proto_init() {
	if File_test_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetPreviewImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetPreviewImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_grpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetPreviewImageSliceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_grpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetPreviewImageSliceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_grpc_proto_goTypes,
		DependencyIndexes: file_test_grpc_proto_depIdxs,
		MessageInfos:      file_test_grpc_proto_msgTypes,
	}.Build()
	File_test_grpc_proto = out.File
	file_test_grpc_proto_rawDesc = nil
	file_test_grpc_proto_goTypes = nil
	file_test_grpc_proto_depIdxs = nil
}
